# Generated by Django 4.0.10 on 2024-01-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_seats_movie_seats_theater_theater_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.theater'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='movie.movie'),
        ),
    ]
